### ISSUE TITLE
SystemJS plugins

### ISSUE THREAD

**Issue by flasaracina** [jsenv/core#37]
Hello!
I am trying to use jsenv for a project, but I cannot find a way to add SystemJS plugins to the mix. I managed to add some babel plugins via `jsenvBabelPluginMap` but I can't do the same for SystemJS's. 

Thank you for your hard work on this. Much appreciated!

**Comment by dmail** [comment]
Hello :)
Unfortunately, it is not possible to configure SystemsJS directly for now.
What are you trying to achieve with SystemsJS plugins?

**Comment by flasaracina** [comment]
What I am trying to achieve is just to be able to call js modules without an extension and make `.js` as the default.
I am porting a framework of mine that is completely pluggable, from the binding system (I am able to mix vue with knockout, etc) to the module loading system. Until now I've been using systemjs 0.2 as a module loader, but I wanted to step up to a newer alternative. I managed to integrate `jsenv` in a few lines of code, but now I need those defaults. I know, because I read another issue on the matter, that you won't support that anytime soon, so I decided to write the plugin myself.

thanks

**Comment by dmail** [comment]
You're refering to https://github.com/jsenv/jsenv-core/issues/34 where I said won't fix for now.

Shortly after closing this issue I needed auto `.js` extension.
There is a not yet documented option called `importDefaultExtension`.
It can be resumed like this: `importDefaultExtension` will be suffixed to any file without extension.

You can use it like this for instance: 

 ```js
const { startExploringServer } = require("@jsenv/core")

startExploringServer({
  importDefaultExtension: '.js',
})
```

For now you cannot expect jsenv to try different extension and choose the right one. If you only need auto `.js` extension on import you will be fine.

**Comment by dmail** [comment]
For your information, importDefautExtension is not yet available on all jsenv repositories. I am going to add it and update documentation accordingly.

**Comment by flasaracina** [comment]
That's sounds like the thing I need!!
I'll try it as soon as I can!

Thank you very much!!!
Hope this project gains the attention it deserves!

**Comment by dmail** [comment]
Cool, let me know if you have any issue.

Also be careful that latest version of a jsenv npm package is unstable.
I'm working to stabilize the whole jsenv ecosystem and sometimes I break stuff that are not inside a major version.
If you want to update a jsenv package, it's safer to use the version documented in the readme, not the latest version available on npm.
