### ISSUE TITLE
Exploring Issues

### ISSUE THREAD

**Issue by FloreGiraudier** [jsenv/core#94]
1/ Compiled files are shown in explorable files. See screenshot below:
![jsenv](https://user-images.githubusercontent.com/39086754/84416836-0a944000-ac15-11ea-9ec0-d6b5101a8a7d.PNG)

2/ As discussed, "All" group should maybe be removed, and instead create 2 "default" groups (source files and unit tests files for ex), in the example file

**Comment by dmail** [comment]
All group removed and compiled files now excluded by default. Thanks :)
